# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: erenon.hu
email: aa@bb.cc
description: > # this means to ignore newlines until "baseurl:"
  Short thoughts on C++, Unix and in general, technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://erenon.hu" # the base hostname & protocol for your site
github_username: erenon
stackoverflow_userid: 116273

# Build settings
markdown: kramdown
