baseURL = "http://erenon.hu/"
languageCode = "en-us"
title = "erenon.hu"

theme = "erenon"

[markup]
[markup.highlight]
style = "perldoc"
noClasses = false

[markup.goldmark]
[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false
[markup.goldmark.renderer]
unsafe = true
