# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "erenon"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"

description = "A slightly customized port of the Jekyll mimina theme"
#homepage = "http://example.com/"
#tags = []
#features = []
#min_version = "0.41.0"

[author]
  name = "erenon"
  homepage = ""

# If porting an existing theme
[original]
  name = "minima"
  homepage = "https://jekyll.github.io/minima/"
  repo = "https://github.com/jekyll/minima"
